function soma (n1=0, n2=0){
    return n1 + n2
}

/* EM N1=0 O IGUAL A ZERO É PARA CASO OS DOIS NÚMEROS NÃO SEJAM CHAMADO
EM BAIXO ELE VAI SER IGUAL A ZERO. SE FOR COLOCADO SOMENTE 
1 NÚMERO VAI SER SOMADO SOMENTE ESSE NÚMERO.
EXEMPLO, SE FOR COLOCADO console.log(soma(7)) A SOMA VAI SER
7  */


console.log(soma(7,2))